import type { AsymptaUniversalLocale } from "./asympta-universal-task-protocol.ts";
import type { SimulationSide } from "./asympta-simulation-compiler.ts";

export const SIMULATION_COPY = {
  usersTitle: ["What would you like to happen?", "你想讓甚麼事情發生？", "何を実現したいですか？"],
  businessTitle: ["What is happening in your business?", "你的生意正在發生甚麼？", "事業で何が起きていますか？"],
  usersHint: ["A request, a plan, or a situation. Start with your own words.", "需求、計劃或遇到的情況，用自己的話開始。", "依頼、計画、困りごとを自分の言葉で。"],
  businessHint: ["Describe an order, your capacity, a shortage, or a change.", "描述訂單、服務能力、缺貨或營運變化。", "注文、対応能力、在庫不足、変更を入力。"],
  input: ["Describe a situation", "描述一個情境", "状況を入力"],
  usersPlaceholder: ["I want to buy a car. Budget: HKD 300000. Compare the options before I decide.", "我想買一架車。\n預算：HKD 300000\n先比較選項，等我決定。", "車を買いたい。\n予算：JPY 4000000\n決める前に候補を比較したい。"],
  businessPlaceholder: ["We have an order for 50 notebooks but only 20 in stock. Find a supplier and confirm a delivery plan.", "我們收到 50 本筆記簿的訂單，但庫存只有 20 本。請聯絡供應商，確認交付計劃。", "ノート50冊の注文が入りましたが在庫は20冊です。仕入先と納期を確認したい。"],
  simulate: ["Simulation", "模擬", "シミュレーション"],
  compile: ["Structure this situation", "整理這個情境", "状況を整理"],
  structured: ["Ready for your agents", "交給代理的資料", "エージェントへの情報"],
  edit: ["Edit situation", "修改情境", "状況を編集"],
  start: ["Confirm & simulate", "確認並開始模擬", "確認して開始"],
  examples: ["Try a situation", "試試一個情境", "状況の例"],
  goal: ["Your intention", "你的意圖", "あなたの意図"],
  budget: ["Budget", "預算", "予算"],
  quantity: ["Quantity", "數量", "数量"],
  deadline: ["Timing", "時間", "時期"],
  location: ["Location", "地點", "場所"],
  constraints: ["Conditions", "條件", "条件"],
  outcome: ["What result should the agents work toward?", "你希望代理達成甚麼結果？", "エージェントに求める結果は？"],
  selected_offer_id: ["Which option would you like to simulate?", "你想模擬哪個選項？", "どの候補を試しますか？"],
  missing: ["One more detail", "再補充一點", "もう少し確認"],
  answer: ["Your answer", "你的回答", "回答"],
  apply: ["Update agent brief", "更新代理資料", "情報を更新"],
  target: ["Requested item or service", "所需物品或服務", "対象の商品・サービス"],
  stock: ["Stock on hand", "現有庫存", "現在の在庫"],
  capacity: ["Capacity", "產能", "対応可能数"],
  capability: ["Business capability", "商家能力", "提供するサービス"],
  facts: ["Details extracted", "已整理的資料", "抽出した情報"],
  noFacts: ["No numeric conditions detected. Your full description stays in the agent brief.", "未辨識到數值條件；完整描述會保留在代理資料中。", "数値条件は未検出です。説明の全文は保持されます。"],
  compilerHint: ["Local rules propose this brief. Review it; unfamiliar details stay in the original text.", "這是本機規則整理的草案，請檢查；未辨識的細節會保留在原文。", "ローカルルールによる提案です。内容を確認してください。未認識の詳細は原文に残ります。"],
  agents: ["Who will coordinate", "參與協作的代理", "連携するエージェント"],
  trace: ["Agent journey", "代理旅程", "エージェントの動き"],
  packet: ["Inspect agent packet", "檢視 agent 資料包", "エージェントのデータを見る"],
  running: ["Agents are coordinating", "代理正在協作", "エージェントが連携中"],
  waiting: ["Your decision is needed", "需要你作決定", "確認が必要です"],
  completed: ["Simulation complete", "模擬已完成", "シミュレーション完了"],
  blocked: ["Simulation stopped", "模擬已停止", "シミュレーション停止"],
  verified: ["The simulated handoffs and return were recorded. No real transaction took place.", "模擬交接與返回已記錄，沒有執行真實交易。", "模擬の引継ぎと帰還を記録しました。実際の取引はありません。"],
  background: ["Continues in background", "可在背景繼續", "バックグラウンドで継続"],
  backgroundDetail: ["Keep this tab open. If your browser suspends it, progress catches up on return, stopping at approvals.", "保留此分頁。若瀏覽器暫停運算，返回時會補算進度，並停在確認關口。", "タブを開いたままにしてください。停止された場合は復帰時に進捗を補い、承認で待機します。"],
  new: ["New situation", "新情境", "新しい状況"],
  open: ["Open simulation studio", "開啟模擬工作區", "シミュレーションを開く"],
  minimize: ["Minimize workspace", "收起工作區", "ワークスペースを閉じる"],
  legacy: ["Use connected tools", "使用已連接工具", "接続ツールを使う"],
  approve: ["Approve simulated plan", "批准模擬方案", "模擬プランを承認"],
  decline: ["Decline", "拒絕", "拒否"],
  approvalNote: ["Approve this simulation step only. It cannot charge, book, publish, or contact a real service.", "只批准這次模擬步驟，並不會扣款、預訂、公開內容或聯络真實服務。", "この模擬手順のみ承認します。実際の決済、予約、公開、連絡は行いません。"],
  activeOther: ["An existing simulation is still active. You can prepare this brief while it finishes.", "另一個模擬仍在進行，你可以先整理這份資料。", "別の模擬が進行中です。その間にこの情報を整理できます。"],
  failed: ["This simulation could not start. Your situation is still here; please try again.", "暫時未能啟動模擬，情境已保留，請再試一次。", "開始できませんでした。入力を保持しています。もう一度お試しください。"],
  tooLong: ["Please keep the situation within 12,000 characters.", "請把情境控制在 12,000 字元內。", "12,000文字以内で入力してください。"],
  intake: ["Receive the agent brief", "接收代理資料", "情報を受信"],
  route: ["Reach the other organisation", "聯絡另一方代理", "相手の組織へ連絡"],
  check: ["Check conditions and resources", "核對條件與資源", "条件と資源を確認"],
  proposal: ["Return a simulated proposal", "交回模擬方案", "模擬プランを提案"],
  approval: ["Review the simulated commitment", "確認模擬承諾", "模擬の確約を確認"],
  execute: ["Carry out the simulated handoff", "執行模擬交接", "模擬の引継ぎを実行"],
  verify: ["Verify the coordination trace", "核實協作記錄", "連携記録を検証"],
  return: ["Bring the simulation result back", "帶回模擬結果", "模擬結果を持ち帰る"],
  "agent-user": ["Personal", "個人", "パーソナル"],
  "agent-customer": ["Customer", "客戶", "顧客"],
  "agent-business": ["Business", "商家", "事業者"],
  "agent-supplier": ["Supplier", "供應商", "仕入先"],
  "agent-operations": ["Operations", "營運", "運用"],
  "agent-finance": ["Approval", "確認", "承認"],
  "agent-quality": ["Verifier", "驗證", "検証"],
  "agent-logistics": ["Logistics", "物流", "物流"],
  "agent-support": ["Support", "支援", "サポート"],
  "agent-market": ["Research", "研究", "調査"],
} as const;
export type SimulationCopyKey = keyof typeof SIMULATION_COPY;
export function simulationText(key: SimulationCopyKey, locale: AsymptaUniversalLocale) {
  return SIMULATION_COPY[key][locale === "zh-Hant" ? 1 : locale === "ja" ? 2 : 0];
}
export const SIMULATION_EXAMPLES: Array<{ side: SimulationSide; title: readonly [string, string, string]; text: readonly [string, string, string] }> = [
  { side: "users", title: ["Buy a car", "買一架車", "車を買う"], text: ["I want to buy a car.\nBudget: HKD 300000", "我想買一架車。\n預算：HKD 300000", "自動車を買いたい。\n予算：HKD 300000"] },
  { side: "users", title: ["Book dinner", "預訂晚餐", "夕食を予約"], text: ["Book dinner for 4 people tomorrow.\nBudget: HKD 800\nConditions: one person is vegetarian", "幫我預訂明晚四人晚餐。\n預算：HKD 800\n條件：一人吃素", "明日の夕食を4人で予約したい。\n予算：HKD 800\n条件：1人はベジタリアン"] },
  { side: "users", title: ["Repair something", "安排維修", "修理を頼む"], text: ["Repair my laptop before Friday. Keep the data intact.", "星期五前維修我的電腦，請保留所有資料。", "金曜日までにパソコンを修理したい。データは保持してください。"] },
  { side: "users", title: ["Plan anything", "自訂情境", "自由な状況"], text: ["Help me organise a neighbourhood singing night.\nOutcome: an agreed plan with a venue and participants", "幫我籌辦社區唱歌之夜。\n目標：確認場地、參與者與活動計劃", "地域の歌の夕べを企画したい。\n結果：会場と参加者を含む合意済みの計画"] },
  { side: "business", title: ["Stock shortage", "庫存不足", "在庫不足"], text: ["We need 50 notebooks for a customer, but have 20 in stock. Find a supplier.\nDeadline: Friday", "客戶需要 50 本筆記簿，但庫存只有 20 本。請聯絡供應商補貨。\n期限：星期五", "顧客の注文はノート50冊、在庫は20冊です。仕入先に補充を依頼したい。\n納期：金曜日"] },
  { side: "business", title: ["Delivery delay", "交付延遲", "配送の遅延"], text: ["Our supplier is delayed by two days. Replan delivery and prepare an update for affected customers.", "供應商延遲兩日。請重新安排交付，準備受影響客戶的更新。", "仕入先が2日遅延します。配送計画を見直し、顧客への案内を準備したい。"] },
  { side: "business", title: ["Service capacity", "服務能力", "サービス枠"], text: ["We offer guitar repairs and have two technicians free on Friday. Match suitable customer requests.", "我們提供吉他維修，星期五有兩位技師可接單。請配對合適客戶需求。", "ギター修理を提供しています。金曜日は技術者2人が対応可能です。適切な依頼を探したい。"] },
  { side: "business", title: ["Custom situation", "自訂情境", "自由な状況"], text: ["We want to offer singing lessons to local residents.\nOutcome: a reviewed service plan and suitable partners", "我們想為附近居民提供唱歌課程。\n目標：可審核的服務計劃與合作伙伴", "近隣の住民に歌のレッスンを提供したい。\n結果：確認できるサービス計画と協力先"] },
];
