import {
  upsertAsymptaServiceManifest,
  type AsymptaServiceManifest,
} from "./asympta-service-registry.ts";

export const SIMULATED_ELECTRONICS_SERVICE: AsymptaServiceManifest = {
  schemaVersion: "asympta.service-manifest.v1",
  serviceId: "simulated.electronics.market",
  version: "1.0.0",
  enabled: true,
  adapter: "atlas_simulation",
  provenance: "bundled_simulated",
  updatedAt: "2026-08-31T00:00:00.000Z",
  labels: {
    en: "Simulated electronics market",
    "zh-Hant": "模擬電子產品市場",
    ja: "シミュレーション家電市場",
  },
  action: {
    id: "purchase",
    phrases: [
      "buy",
      "purchase",
      "order",
      "get me",
      "i want",
      "i need",
      "購買",
      "買",
      "幫我買",
      "我要",
      "購入",
      "買いたい",
    ],
  },
  itemTypes: [
    {
      id: "television",
      domain: "electronics",
      canonicalItem: "television",
      labels: {
        en: "Television",
        "zh-Hant": "電視機",
        ja: "テレビ",
      },
      phrases: [
        "television",
        "smart tv",
        "tv",
        "電視機",
        "電視",
        "智能電視",
        "电视机",
        "电视",
        "テレビ",
      ],
      marketLocationId: "ueno",
    },
  ],
  excludePhrases: [
    "tv show",
    "television programme",
    "television program",
    "電視節目",
    "电视剧",
  ],
  requirements: [
    {
      id: "screen-size",
      capability: "electronics.select",
      field: "screen_size",
      stage: "selection",
      blocking: true,
      priority: 98,
      userEffort: 1,
      description: {
        en: "The electronics service needs one screen-size range to select a compatible simulated television.",
        "zh-Hant": "電子產品服務需要一個螢幕尺寸，才能選擇合適的模擬電視機。",
        ja: "適切なシミュレーションテレビを選ぶには画面サイズが必要です。",
      },
      appliesToItemTypes: ["television"],
      acceptedValues: ["43_inch", "55_inch", "65_inch"],
      question: {
        prompt: {
          en: "Which television size should the agent choose?",
          "zh-Hant": "想讓代理選擇哪一個電視尺寸？",
          ja: "エージェントにどのテレビサイズを選ばせますか？",
        },
        answerType: "single_choice",
        options: [
          { value: "43_inch", label: { en: "43 inch", "zh-Hant": "43 吋", ja: "43インチ" } },
          { value: "55_inch", label: { en: "55 inch", "zh-Hant": "55 吋", ja: "55インチ" } },
          { value: "65_inch", label: { en: "65 inch", "zh-Hant": "65 吋", ja: "65インチ" } },
        ],
        remember: "offer",
      },
      valueMatchers: [
        { value: "43_inch", phrases: ["43 inch", "43-inch", "43吋", "43 寸", "43インチ"] },
        { value: "55_inch", phrases: ["55 inch", "55-inch", "55吋", "55 寸", "55インチ"] },
        { value: "65_inch", phrases: ["65 inch", "65-inch", "65吋", "65 寸", "65インチ"] },
      ],
    },
    {
      id: "fulfilment",
      capability: "electronics.fulfil",
      field: "fulfilment_mode",
      stage: "commitment",
      blocking: true,
      priority: 90,
      userEffort: 1,
      description: {
        en: "The service must know whether the personal agent collects the item or a courier delivers it.",
        "zh-Hant": "服務必須知道由個人代理自取，還是由速遞代理送貨。",
        ja: "個人エージェントの受取か配達かを決める必要があります。",
      },
      acceptedValues: ["personal_agent_pickup", "courier_delivery"],
      question: {
        prompt: {
          en: "Should your personal agent collect it, or should a courier deliver it?",
          "zh-Hant": "由你的個人代理自取，還是由速遞代理送貨？",
          ja: "個人エージェントが受け取りますか、それとも配達しますか？",
        },
        answerType: "single_choice",
        options: [
          { value: "personal_agent_pickup", label: { en: "Personal agent pickup", "zh-Hant": "個人代理自取", ja: "個人エージェント受取" } },
          { value: "courier_delivery", label: { en: "Courier delivery", "zh-Hant": "速遞送貨", ja: "配達" } },
        ],
        remember: "offer",
      },
      valueMatchers: [
        { value: "personal_agent_pickup", phrases: ["personal agent pickup", "agent pickup", "pick it up", "自取", "個人代理自取", "個人エージェント受取"] },
        { value: "courier_delivery", phrases: ["courier delivery", "deliver it", "delivery", "送貨", "速遞", "配送", "配達"] },
      ],
    },
    {
      id: "payment",
      capability: "electronics.pay",
      field: "payment_method",
      stage: "commitment",
      blocking: true,
      priority: 85,
      userEffort: 1,
      description: {
        en: "A safe payment-method alias is required before the simulated finance agent can continue.",
        "zh-Hant": "模擬付款代理繼續前，需要一個安全的付款方式代號。",
        ja: "シミュレーション支払いを続けるには支払い方法が必要です。",
      },
      acceptedValues: ["asympta_wallet", "card_on_file", "pay_on_delivery"],
      question: {
        prompt: {
          en: "Which simulated payment method should this request use?",
          "zh-Hant": "今次模擬交易使用哪一種付款方式？",
          ja: "今回のシミュレーションで使う支払い方法はどれですか？",
        },
        answerType: "single_choice",
        options: [
          { value: "asympta_wallet", label: { en: "Asympta Wallet", "zh-Hant": "Asympta 錢包", ja: "Asympta Wallet" } },
          { value: "card_on_file", label: { en: "Card on file", "zh-Hant": "已登記卡", ja: "登録カード" } },
          { value: "pay_on_delivery", label: { en: "Pay on delivery", "zh-Hant": "貨到付款", ja: "代引き" } },
        ],
        remember: "offer",
      },
      valueMatchers: [
        { value: "asympta_wallet", phrases: ["asympta wallet", "wallet", "錢包", "钱包"] },
        { value: "card_on_file", phrases: ["card on file", "registered card", "已登記卡", "登録カード"] },
        { value: "pay_on_delivery", phrases: ["pay on delivery", "cash on delivery", "貨到付款", "代引き"] },
      ],
    },
  ],
  permissions: [
    { action: "query_simulated_electronics_market", mode: "allowed" },
    { action: "reserve_simulated_inventory", mode: "allowed" },
    { action: "execute_simulated_delivery", mode: "allowed" },
    { action: "place_real_order", mode: "prohibited", reason: "This service manifest is simulation-only." },
    { action: "charge_real_payment_method", mode: "prohibited", reason: "Only a payment alias is used in the simulation." },
  ],
  successCriteria: [
    { id: "electronics-service-accepted", description: "The electronics service accepts the structured request.", requiredEvidence: ["service_acceptance"] },
    { id: "electronics-stock-confirmed", description: "The simulated item is confirmed and allocated.", requiredEvidence: ["inventory_confirmation"] },
    { id: "electronics-delivered", description: "The simulated television reaches the user.", requiredEvidence: ["completion_receipt"] },
  ],
  workflow: {
    name: {
      en: "Electronics purchase · {{requested_item}}",
      "zh-Hant": "電子產品購買 · {{requested_item}}",
      ja: "家電購入 · {{requested_item}}",
    },
    shortName: { en: "Electronics", "zh-Hant": "電子產品", ja: "家電" },
    summary: {
      en: "A versioned service manifest turns the request into electronics selection, stock, payment and delivery work.",
      "zh-Hant": "版本化服務清單把請求轉換成電子產品選擇、庫存、付款及配送工作。",
      ja: "バージョン付きサービス定義が選択・在庫・支払い・配達を調整します。",
    },
    outcome: {
      en: "The simulated {{screen_size}} {{requested_item}} is delivered to the user.",
      "zh-Hant": "模擬的 {{screen_size}} {{requested_item}} 已交付給使用者。",
      ja: "シミュレーションの {{screen_size}} {{requested_item}} をユーザーへ配達しました。",
    },
    tasks: [
      {
        id: "context",
        title: { en: "Compile service task", "zh-Hant": "編譯服務任務", ja: "サービスタスクを構築" },
        detail: { en: "Resolve the current request, approved profile and service version into one ready task.", "zh-Hant": "把目前請求、已批准偏好及服務版本整理成可執行任務。", ja: "依頼・承認済み設定・サービス版を実行可能なタスクにまとめます。" },
        agentId: "agent-user",
        locationId: "$home",
        dependsOn: [],
        workMs: 700,
      },
      {
        id: "market",
        title: { en: "Find a compatible {{screen_size}} television", "zh-Hant": "尋找合適的 {{screen_size}} 電視機", ja: "適合する {{screen_size}} テレビを検索" },
        detail: { en: "The market agent evaluates the simulated electronics catalogue for the requested size.", "zh-Hant": "市場代理按所需尺寸檢查模擬電子產品目錄。", ja: "市場エージェントが指定サイズの模擬カタログを確認します。" },
        agentId: "agent-market",
        locationId: "$market",
        dependsOn: ["context"],
        workMs: 900,
      },
      {
        id: "store",
        title: { en: "Store agent prepares an offer", "zh-Hant": "商店代理準備方案", ja: "店舗エージェントが提案を作成" },
        detail: { en: "Create a bounded simulated offer using the service contract and current preferences.", "zh-Hant": "使用服務合約及目前偏好建立受限的模擬方案。", ja: "サービス契約と現在の設定から限定的な提案を作成します。" },
        agentId: "agent-business",
        locationId: "$market",
        dependsOn: ["market"],
        workMs: 900,
      },
      {
        id: "stock",
        title: { en: "Supplier confirms simulated stock", "zh-Hant": "供應代理確認模擬庫存", ja: "供給エージェントが模擬在庫を確認" },
        detail: { en: "Confirm one {{requested_item}} without claiming live external inventory.", "zh-Hant": "確認一部 {{requested_item}}，但不聲稱是真實外部庫存。", ja: "外部の実在庫とは主張せず {{requested_item}} を確認します。" },
        agentId: "agent-supplier",
        locationId: "$market",
        dependsOn: ["store"],
        workMs: 900,
      },
      {
        id: "quality",
        title: { en: "Quality agent verifies compatibility", "zh-Hant": "品質代理驗證相容性", ja: "品質エージェントが適合性を検証" },
        detail: { en: "Check size, service provenance and the declared completion criteria.", "zh-Hant": "檢查尺寸、服務來源及已宣告的完成條件。", ja: "サイズ・サービス由来・完了条件を確認します。" },
        agentId: "agent-quality",
        locationId: "nihonbashi",
        dependsOn: ["stock"],
        workMs: 800,
      },
      {
        id: "finance",
        title: { en: "Finance agent validates simulated payment", "zh-Hant": "付款代理驗證模擬付款", ja: "支払いエージェントが模擬決済を確認" },
        detail: { en: "Use the approved payment alias without charging a real payment method.", "zh-Hant": "使用已批准的付款方式代號，但不會扣取真實款項。", ja: "承認済みの支払い別名を使い、実際の請求は行いません。" },
        agentId: "agent-finance",
        locationId: "otemachi",
        dependsOn: ["quality"],
        workMs: 750,
      },
      {
        id: "collect",
        title: { en: "Carrier collects the television", "zh-Hant": "配送代理領取電視機", ja: "配送エージェントがテレビを受取" },
        detail: { en: "The selected fulfilment method determines the simulated carrier handoff.", "zh-Hant": "已選配送方式決定模擬交接代理。", ja: "選択した受取方法に従って引き渡します。" },
        agentId: "agent-logistics",
        locationId: "$market",
        dependsOn: ["finance"],
        workMs: 800,
      },
      {
        id: "deliver",
        title: { en: "Deliver {{requested_item}} to the user", "zh-Hant": "把 {{requested_item}} 送回使用者", ja: "{{requested_item}} をユーザーへ配達" },
        detail: { en: "Move the simulated item to the user handoff location.", "zh-Hant": "把模擬物品移動至使用者交付地點。", ja: "模擬商品をユーザーの受取地点へ運びます。" },
        agentId: "agent-logistics",
        locationId: "$home",
        dependsOn: ["collect"],
        workMs: 650,
      },
      {
        id: "receipt",
        title: { en: "Verify completion receipt", "zh-Hant": "驗證完成收據", ja: "完了レシートを検証" },
        detail: { en: "Confirm the service version, task facts and final simulated delivery state.", "zh-Hant": "確認服務版本、任務資料及最終模擬交付狀態。", ja: "サービス版・タスク情報・最終配達状態を確認します。" },
        agentId: "agent-support",
        locationId: "$home",
        dependsOn: ["deliver"],
        workMs: 650,
      },
    ],
  },
};

export function ensureBundledAsymptaServices() {
  return [upsertAsymptaServiceManifest(SIMULATED_ELECTRONICS_SERVICE)];
}
